// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxzeotzqpeguzeijxcai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4emVvdHpxcGVndXplaWp4Y2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTc1NjcsImV4cCI6MjA2NDE3MzU2N30.oABpEwqRG82kpj_VzCMZqf7S3TBgjiwANGSQi00w4Qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);